[features]
seeds = false
skip-lint = false
[programs.mainnet]
payment_router = "6pca6uGGV5GYKY8W9aGfJbWPx4pe5mW8wLaP9c3LUNpp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-create-payment-router-balance-pda= "yarn run ts-mocha -g 'pda' -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-route= "yarn run ts-mocha -g 'routes' -p ./tsconfig.json -t 1000000 tests/**/*.ts"
