[features]
seeds = false
skip-lint = false
[programs.mainnet]
staking_bridge = "HEDM7Zg7wNVSCWpV4TF7zp6rgj44C43CXnLtpY68V7bV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-create-staking-bridge-balance-pda= "yarn run ts-mocha -g 'pda' -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-create-staking-bridge-balance-atas= "yarn run ts-mocha -g 'associated' -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-raydium-swap= "yarn run ts-mocha -g 'swap' -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-wormhole-transfer= "yarn run ts-mocha -g 'wormhole' -p ./tsconfig.json -t 1000000 tests/**/*.ts"
